services:
  perplexica:
    build:
      context: .
    # image: itzcrazykns1337/perplexica:latest
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - '3000:3000'
    volumes:
      - ./logs:/home/perplexica/app/logs
    #   - ./data:/home/perplexica/data
      # - uploads:/home/perplexica/uploads
    restart: unless-stopped
    networks:
      # - microservices-network
      - common_net


volumes:
  data:
    name: 'perplexica-data'
  uploads:
    name: 'perplexica-uploads'

networks:
  microservices-network:
    driver: bridge
  common_net:
    external: true
    name: common_network